export const mockQuestions = [
  {
    id: 1,
    title: "Design a feature for Instagram Stories",
    category: "Product Design",
    difficulty: "Medium",
    timeLimit: 45,
    description:
      "Instagram wants to increase user engagement with Stories. Design a new feature that would encourage more users to create and share Stories regularly.",
    prompt:
      "Consider the current user journey, pain points, and opportunities for improvement. Think about different user segments and their motivations.",
    tags: ["Social Media", "User Engagement", "Mobile"],
    attempts: 1247,
    avgScore: 7.2,
    isHot: true,
  },
  {
    id: 2,
    title: "Prioritize features for a food delivery app",
    category: "Product Strategy",
    difficulty: "Hard",
    timeLimit: 60,
    description:
      "You're the PM for a food delivery startup. You have limited engineering resources and need to prioritize the next quarter's features.",
    prompt:
      "Given constraints of 2 engineers for 3 months, choose from: AI-powered recommendations, group ordering, subscription model, restaurant analytics dashboard, customer loyalty program.",
    tags: ["Prioritization", "Strategy", "B2C"],
    attempts: 892,
    avgScore: 6.8,
    isHot: true,
  },
  {
    id: 3,
    title: "Estimate market size for smart home devices",
    category: "Market Sizing",
    difficulty: "Medium",
    timeLimit: 30,
    description: "Calculate the total addressable market (TAM) for smart home devices in the United States.",
    prompt:
      "Break down your approach step by step. Consider different device categories, adoption rates, and market trends.",
    tags: ["Market Analysis", "IoT", "Estimation"],
    attempts: 654,
    avgScore: 7.5,
    isHot: false,
  },
  {
    id: 4,
    title: "Root cause analysis: App crashes increased 300%",
    category: "Analytics",
    difficulty: "Hard",
    timeLimit: 45,
    description:
      "Your mobile app's crash rate suddenly increased from 0.5% to 2% over the past week. Investigate and propose solutions.",
    prompt: "Walk through your investigation process. What data would you look at? What hypotheses would you test?",
    tags: ["Analytics", "Problem Solving", "Mobile"],
    attempts: 423,
    avgScore: 6.9,
    isHot: false,
  },
  {
    id: 5,
    title: "Launch strategy for AI writing assistant",
    category: "Go-to-Market",
    difficulty: "Hard",
    timeLimit: 60,
    description: "You're launching an AI-powered writing assistant. Develop a comprehensive go-to-market strategy.",
    prompt:
      "Consider target segments, pricing strategy, distribution channels, competitive positioning, and success metrics.",
    tags: ["GTM", "AI", "B2B", "SaaS"],
    attempts: 789,
    avgScore: 7.1,
    isHot: true,
  },
  {
    id: 6,
    title: "Design a payment flow for e-commerce",
    category: "Product Design",
    difficulty: "Medium",
    timeLimit: 40,
    description: "Redesign the checkout experience for a major e-commerce platform to reduce cart abandonment.",
    prompt: "Focus on user experience, security concerns, and conversion optimization.",
    tags: ["E-commerce", "UX", "Payments"],
    attempts: 567,
    avgScore: 7.8,
    isHot: false,
  },
  {
    id: 7,
    title: "Metrics for a social media platform",
    category: "Analytics",
    difficulty: "Medium",
    timeLimit: 35,
    description: "Define key metrics for a new social media platform focused on professional networking.",
    prompt: "Consider user engagement, growth, monetization, and platform health metrics.",
    tags: ["Social Media", "Metrics", "B2B"],
    attempts: 445,
    avgScore: 7.3,
    isHot: false,
  },
  {
    id: 8,
    title: "Competitive analysis: Streaming services",
    category: "Product Strategy",
    difficulty: "Hard",
    timeLimit: 50,
    description: "Analyze the competitive landscape for video streaming services and recommend strategic moves.",
    prompt: "Compare Netflix, Disney+, HBO Max, and Amazon Prime. What would you do differently?",
    tags: ["Competition", "Strategy", "Entertainment"],
    attempts: 334,
    avgScore: 6.5,
    isHot: true,
  },
]

export const mockVideos = [
  {
    id: 1,
    title: "How to Structure Product Design Questions",
    instructor: "Sarah Chen",
    duration: "12:34",
    thumbnail: "/placeholder.svg?height=180&width=320",
    category: "Product Design",
    views: 15420,
    rating: 4.8,
    description: "Learn the proven framework for tackling any product design question in PM interviews.",
    publishedAt: "2024-01-15",
    level: "Beginner",
  },
  {
    id: 2,
    title: "Market Sizing: The Complete Guide",
    instructor: "David Rodriguez",
    duration: "18:45",
    thumbnail: "/placeholder.svg?height=180&width=320",
    category: "Market Sizing",
    views: 12890,
    rating: 4.9,
    description: "Master the art of market sizing with real examples from FAANG interviews.",
    publishedAt: "2024-01-10",
    level: "Intermediate",
  },
  {
    id: 3,
    title: "Prioritization Frameworks That Actually Work",
    instructor: "Emily Johnson",
    duration: "15:22",
    thumbnail: "/placeholder.svg?height=180&width=320",
    category: "Product Strategy",
    views: 18750,
    rating: 4.7,
    description: "Deep dive into RICE, ICE, and other frameworks used by top PMs.",
    publishedAt: "2024-01-08",
    level: "Advanced",
  },
  {
    id: 4,
    title: "Analytics Deep Dive: Finding Root Causes",
    instructor: "Michael Park",
    duration: "20:15",
    thumbnail: "/placeholder.svg?height=180&width=320",
    category: "Analytics",
    views: 9340,
    rating: 4.6,
    description: "Learn systematic approaches to investigate product metrics and find actionable insights.",
    publishedAt: "2024-01-05",
    level: "Advanced",
  },
  {
    id: 5,
    title: "Behavioral Interview Mastery",
    instructor: "Lisa Wang",
    duration: "14:28",
    thumbnail: "/placeholder.svg?height=180&width=320",
    category: "Interview Skills",
    views: 22100,
    rating: 4.9,
    description: "Master the STAR method and common behavioral questions for PM roles.",
    publishedAt: "2024-01-12",
    level: "Beginner",
  },
  {
    id: 6,
    title: "Technical PM Skills: APIs and Databases",
    instructor: "Alex Kumar",
    duration: "25:33",
    thumbnail: "/placeholder.svg?height=180&width=320",
    category: "Technical",
    views: 8750,
    rating: 4.5,
    description: "Essential technical knowledge every PM should have about APIs, databases, and system design.",
    publishedAt: "2024-01-03",
    level: "Intermediate",
  },
]

export const mockTestimonials = [
  {
    id: 1,
    name: "Alex Thompson",
    role: "Senior PM at Meta",
    content:
      "ProdSchool helped me land my dream job at Meta. The practice questions are incredibly realistic and the AI feedback is spot-on.",
    avatar: "/placeholder.svg?height=40&width=40",
    rating: 5,
    company: "Meta",
    previousRole: "APM at Google",
  },
  {
    id: 2,
    name: "Priya Patel",
    role: "PM at Google",
    content:
      "The structured approach and peer reviews gave me the confidence I needed. Highly recommend for anyone serious about PM interviews.",
    avatar: "/placeholder.svg?height=40&width=40",
    rating: 5,
    company: "Google",
    previousRole: "Product Analyst at Uber",
  },
  {
    id: 3,
    name: "James Wilson",
    role: "PM at Stripe",
    content: "Best investment I made for my career. The video explanations and practice sessions are top-notch.",
    avatar: "/placeholder.svg?height=40&width=40",
    rating: 5,
    company: "Stripe",
    previousRole: "Consultant at McKinsey",
  },
  {
    id: 4,
    name: "Lisa Chang",
    role: "PM at Airbnb",
    content: "ProdSchool's AI feedback helped me identify my weak spots and improve systematically. Game changer!",
    avatar: "/placeholder.svg?height=40&width=40",
    rating: 5,
    company: "Airbnb",
    previousRole: "PM at Lyft",
  },
  {
    id: 5,
    name: "Marcus Johnson",
    role: "Senior PM at Netflix",
    content: "The community aspect is incredible. Learning from peers who are also preparing made all the difference.",
    avatar: "/placeholder.svg?height=40&width=40",
    rating: 5,
    company: "Netflix",
    previousRole: "PM at Spotify",
  },
  {
    id: 6,
    name: "Sofia Rodriguez",
    role: "PM at Microsoft",
    content: "From zero PM experience to landing at Microsoft in 6 months. The structured curriculum works!",
    avatar: "/placeholder.svg?height=40&width=40",
    rating: 5,
    company: "Microsoft",
    previousRole: "Software Engineer at Amazon",
  },
]

export const mockAttempts = [
  {
    id: 1,
    questionId: 1,
    date: "2024-01-15",
    score: 8.2,
    timeSpent: 42,
    feedback: "Strong framework and user-centric thinking. Consider exploring edge cases more thoroughly.",
    status: "completed",
    response: "I would approach this by first understanding the current user journey...",
    aiInsights: {
      strengths: ["Clear problem identification", "User-centric approach", "Structured thinking"],
      improvements: ["Consider technical constraints", "Add success metrics", "Explore edge cases"],
    },
  },
  {
    id: 2,
    questionId: 2,
    date: "2024-01-14",
    score: 7.5,
    timeSpent: 58,
    feedback: "Good prioritization logic. Could improve on stakeholder consideration and technical feasibility.",
    status: "completed",
    response: "Given the constraints, I would prioritize features using the RICE framework...",
    aiInsights: {
      strengths: ["Good framework usage", "Clear reasoning", "Resource awareness"],
      improvements: ["Stakeholder analysis", "Technical feasibility", "Risk assessment"],
    },
  },
  {
    id: 3,
    questionId: 3,
    date: "2024-01-13",
    score: 6.8,
    timeSpent: 35,
    feedback: "Solid market sizing approach. Work on breaking down assumptions more clearly.",
    status: "completed",
    response: "To estimate the TAM for smart home devices, I'll use a bottom-up approach...",
    aiInsights: {
      strengths: ["Logical structure", "Good data sources", "Clear calculations"],
      improvements: ["Assumption validation", "Market segmentation", "Growth projections"],
    },
  },
]

export const mockPeerReviews = [
  {
    id: 1,
    reviewerId: "user123",
    reviewerName: "Sarah M.",
    reviewerRole: "PM at Google",
    questionId: 1,
    score: 8,
    feedback:
      "Great structure and clear thinking. Your user segmentation was particularly strong. One suggestion: consider the technical implementation challenges more deeply.",
    date: "2024-01-16",
    helpful: 12,
    response: "Thank you for the detailed feedback! You're right about the technical constraints.",
  },
  {
    id: 2,
    reviewerId: "user456",
    reviewerName: "David L.",
    reviewerRole: "Senior PM at Meta",
    questionId: 1,
    score: 7,
    feedback:
      "Good framework application. The solution is creative but might be too complex for an MVP. Consider starting simpler.",
    date: "2024-01-16",
    helpful: 8,
    response: "Great point about MVP complexity. I'll focus on simpler solutions first.",
  },
  {
    id: 3,
    reviewerId: "user789",
    reviewerName: "Emily R.",
    reviewerRole: "PM at Stripe",
    questionId: 2,
    score: 9,
    feedback:
      "Excellent prioritization framework! Your RICE scoring was thorough and well-reasoned. Minor suggestion: add more detail on implementation timeline.",
    date: "2024-01-15",
    helpful: 15,
    response: "Thanks! I'll definitely add more timeline considerations in future responses.",
  },
]

export const mockCommunityPosts = [
  {
    id: 1,
    title: "How to prepare for Google PM interviews?",
    content:
      "I have a Google PM interview coming up in 3 weeks. What should I focus on? Any specific frameworks or resources you'd recommend?",
    author: {
      name: "Alex Chen",
      role: "Software Engineer",
      avatar: "/placeholder.svg?height=40&width=40",
      level: "Beginner",
    },
    category: "Interview Prep",
    tags: ["Google", "Interview", "Frameworks"],
    createdAt: "2024-01-16T10:30:00Z",
    updatedAt: "2024-01-16T10:30:00Z",
    likes: 24,
    replies: 8,
    views: 156,
    isLiked: false,
    isPinned: false,
    lastReply: {
      author: "Sarah M.",
      content: "Focus on product design and analytical questions. Google loves structured thinking!",
      createdAt: "2024-01-16T14:20:00Z",
    },
  },
  {
    id: 2,
    title: "Meta PM Interview Experience - L5 Role",
    content:
      "Just finished my Meta PM interview loop. Happy to share my experience and answer questions! The process was intense but fair. Here's what I learned...",
    author: {
      name: "Priya Patel",
      role: "PM at Uber",
      avatar: "/placeholder.svg?height=40&width=40",
      level: "Advanced",
    },
    category: "Interview Experience",
    tags: ["Meta", "L5", "Experience"],
    createdAt: "2024-01-15T16:45:00Z",
    updatedAt: "2024-01-15T16:45:00Z",
    likes: 67,
    replies: 23,
    views: 445,
    isLiked: true,
    isPinned: true,
    lastReply: {
      author: "Mike J.",
      content: "Congrats! How did you prepare for the execution round?",
      createdAt: "2024-01-16T09:15:00Z",
    },
  },
  {
    id: 3,
    title: "Best resources for market sizing practice?",
    content:
      "I'm struggling with market sizing questions. The numbers always seem off and I'm not confident in my approach. What resources helped you master this?",
    author: {
      name: "Jordan Kim",
      role: "Business Analyst",
      avatar: "/placeholder.svg?height=40&width=40",
      level: "Intermediate",
    },
    category: "Study Resources",
    tags: ["Market Sizing", "Practice", "Resources"],
    createdAt: "2024-01-15T09:20:00Z",
    updatedAt: "2024-01-15T09:20:00Z",
    likes: 18,
    replies: 12,
    views: 234,
    isLiked: false,
    isPinned: false,
    lastReply: {
      author: "Lisa W.",
      content: "Check out the Fermi estimation guide in the resources section!",
      createdAt: "2024-01-15T18:30:00Z",
    },
  },
  {
    id: 4,
    title: "Transitioning from Engineering to PM - Timeline?",
    content:
      "I'm a senior software engineer looking to transition to PM. How long should I expect the preparation process to take? Currently spending 1-2 hours daily on ProdSchool.",
    author: {
      name: "Marcus Thompson",
      role: "Senior SWE",
      avatar: "/placeholder.svg?height=40&width=40",
      level: "Beginner",
    },
    category: "Career Transition",
    tags: ["Engineering", "Transition", "Timeline"],
    createdAt: "2024-01-14T20:15:00Z",
    updatedAt: "2024-01-14T20:15:00Z",
    likes: 31,
    replies: 16,
    views: 298,
    isLiked: true,
    isPinned: false,
    lastReply: {
      author: "David R.",
      content: "Took me about 4-6 months with consistent practice. Your engineering background is a huge advantage!",
      createdAt: "2024-01-15T11:45:00Z",
    },
  },
  {
    id: 5,
    title: "Amazon Leadership Principles in PM interviews",
    content:
      "For those who've interviewed at Amazon, how heavily do they weigh the leadership principles in PM interviews? Any specific examples you can share?",
    author: {
      name: "Sofia Martinez",
      role: "Product Analyst",
      avatar: "/placeholder.svg?height=40&width=40",
      level: "Intermediate",
    },
    category: "Company Specific",
    tags: ["Amazon", "Leadership Principles", "Behavioral"],
    createdAt: "2024-01-14T14:30:00Z",
    updatedAt: "2024-01-14T14:30:00Z",
    likes: 22,
    replies: 9,
    views: 187,
    isLiked: false,
    isPinned: false,
    lastReply: {
      author: "Alex T.",
      content: "They're crucial! Every answer should tie back to at least one LP. Practice STAR method extensively.",
      createdAt: "2024-01-14T19:20:00Z",
    },
  },
]

export const mockCommunityReplies = [
  {
    id: 1,
    postId: 1,
    content:
      "Focus on product design and analytical questions. Google loves structured thinking! I'd recommend practicing with the CIRCLES method for design questions.",
    author: {
      name: "Sarah M.",
      role: "PM at Google",
      avatar: "/placeholder.svg?height=32&width=32",
      level: "Expert",
    },
    createdAt: "2024-01-16T14:20:00Z",
    likes: 8,
    isLiked: false,
    replies: [
      {
        id: 11,
        content: "Thanks Sarah! Any specific practice questions you'd recommend?",
        author: {
          name: "Alex Chen",
          role: "Software Engineer",
          avatar: "/placeholder.svg?height=32&width=32",
          level: "Beginner",
        },
        createdAt: "2024-01-16T15:30:00Z",
        likes: 2,
        isLiked: false,
      },
    ],
  },
  {
    id: 2,
    postId: 1,
    content:
      "Also practice estimation questions! Google asks a lot of market sizing and back-of-envelope calculations.",
    author: {
      name: "Mike Johnson",
      role: "Ex-Google PM",
      avatar: "/placeholder.svg?height=32&width=32",
      level: "Expert",
    },
    createdAt: "2024-01-16T16:45:00Z",
    likes: 5,
    isLiked: true,
    replies: [],
  },
]

export const mockMetrics = {
  totalQuestions: 150,
  totalUsers: 12500,
  avgImprovement: 85,
  successRate: 92,
  totalVideos: 45,
  totalCommunityPosts: 1250,
  activeUsers: 3400,
  questionsAnswered: 45600,
}

export const mockCompanies = [
  { name: "Google", logo: "/placeholder.svg?height=40&width=40", openings: 23 },
  { name: "Meta", logo: "/placeholder.svg?height=40&width=40", openings: 18 },
  { name: "Amazon", logo: "/placeholder.svg?height=40&width=40", openings: 31 },
  { name: "Apple", logo: "/placeholder.svg?height=40&width=40", openings: 12 },
  { name: "Microsoft", logo: "/placeholder.svg?height=40&width=40", openings: 27 },
  { name: "Netflix", logo: "/placeholder.svg?height=40&width=40", openings: 8 },
  { name: "Stripe", logo: "/placeholder.svg?height=40&width=40", openings: 15 },
  { name: "Airbnb", logo: "/placeholder.svg?height=40&width=40", openings: 9 },
]

export const mockLeaderboard = [
  {
    rank: 1,
    name: "Sarah Chen",
    avatar: "/placeholder.svg?height=32&width=32",
    score: 2847,
    questionsCompleted: 89,
    streak: 23,
    badge: "🏆",
  },
  {
    rank: 2,
    name: "David Rodriguez",
    avatar: "/placeholder.svg?height=32&width=32",
    score: 2756,
    questionsCompleted: 76,
    streak: 18,
    badge: "🥈",
  },
  {
    rank: 3,
    name: "Emily Johnson",
    avatar: "/placeholder.svg?height=32&width=32",
    score: 2689,
    questionsCompleted: 82,
    streak: 15,
    badge: "🥉",
  },
  {
    rank: 4,
    name: "Michael Park",
    avatar: "/placeholder.svg?height=32&width=32",
    score: 2634,
    questionsCompleted: 71,
    streak: 12,
    badge: "⭐",
  },
  {
    rank: 5,
    name: "Lisa Wang",
    avatar: "/placeholder.svg?height=32&width=32",
    score: 2598,
    questionsCompleted: 68,
    streak: 20,
    badge: "⭐",
  },
]

export const mockNotifications = [
  {
    id: 1,
    type: "achievement",
    title: "New Achievement Unlocked!",
    message: "You've earned the 'Week Streak' badge for practicing 7 days in a row.",
    createdAt: "2024-01-16T10:30:00Z",
    read: false,
    icon: "🏆",
  },
  {
    id: 2,
    type: "peer_review",
    title: "New Peer Review",
    message: "Sarah M. reviewed your response to 'Design a feature for Instagram Stories'",
    createdAt: "2024-01-16T09:15:00Z",
    read: false,
    icon: "👥",
  },
  {
    id: 3,
    type: "ai_feedback",
    title: "AI Feedback Ready",
    message: "Your response to 'Market sizing for smart home devices' has been analyzed.",
    createdAt: "2024-01-15T18:45:00Z",
    read: true,
    icon: "🤖",
  },
  {
    id: 4,
    type: "community",
    title: "Popular Discussion",
    message: "Your post 'Google PM Interview Tips' is trending in the community!",
    createdAt: "2024-01-15T14:20:00Z",
    read: true,
    icon: "💬",
  },
]
